### ISSUE TITLE
Line numbers in editors

### ISSUE THREAD

**Issue by lpillmann** [nolanbconaway/sqlfluff-online#6]
Hi @nolanbconaway!

I've just discovered the app and really liked it.

As I tried some examples, I was having to count the lines so I could go back to my original SQL and learn where it was wrong. Just thought it would look really cool if we had some line numbers in there, so that the lookup would be easier.

I understand the main use case would just copy-pasting the final result. But I guess learning where it was wrong might be useful for folks willing to understand the rules being applied, as it was for me in this case.

Glad to be inaugurating the issues in here, btw!

**Comment by nolanbconaway** [comment]
Sounds like a great idea! Are you up for a PR? If not, I'll get to it eventually.

**Comment by lpillmann** [comment]
Sure! I can take a look at that.
